### ISSUE TITLE
Hello! I have an issue with framework. Help me, please. 

### ISSUE THREAD

**Issue by Antonkl22** [Smithsonian/dpo-cook#48]
Hello! 
I have done all steps from the "Getting sterted" manual, but every time when i am trying to launch server it crashes. Could you tell me, please, how to repair it? Here the listing from CMD bellow.       

C:\1DMod\dpo-cook>npm run server

> dpo-cook@1.0.0 server C:\1DMod\dpo-cook
> node server/bin/index.js

  _________       .__  __  .__                        .__                ________ ________
 /   _____/ _____ |__|/  |_|  |__   __________   ____ |__|____    ____   \_____  \\______ \
 \_____  \ /     \|  \   __\  |  \ /  ___/  _ \ /    \|  \__  \  /    \    _(__  < |    |  \
 /        \  Y Y  \  ||  | |   Y  \\___ (  <_> )   |  \  |/ __ \|   |  \  /       \|    `   \
/_______  /__|_|  /__||__| |___|  /____  >____/|___|  /__(____  /___|  / /______  /_______  /
        \/      \/              \/     \/           \/        \/     \/         \/        \/

-------------------------
Cook 3D Processing Server
-------------------------

Clients loaded: 2

C:\1DMod\dpo-cook\source\server\utils\jsonLoader.ts:69
    return validate(filePath);

Error: failed to validate 'C:\1DMod\dpo-cook\server\tools.json': data['InstantMeshes'].version should NOT be shorter than 1 characters
    at C:\1DMod\dpo-cook\source\server\utils\jsonLoader.ts:59:19
    at Object.validate (C:\1DMod\dpo-cook\source\server\utils\jsonLoader.ts:69:12)
    at new TaskManager (C:\1DMod\dpo-cook\source\server\app\TaskManager.ts:47:46)
    at new JobManager (C:\1DMod\dpo-cook\source\server\app\JobManager.ts:139:28)
    at new ProcessingServer (C:\1DMod\dpo-cook\source\server\app\ProcessingServer.ts:78:27)
    at Object.<anonymous> (C:\1DMod\dpo-cook\source\server\index.ts:41:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dpo-cook@1.0.0 server: `node server/bin/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dpo-cook@1.0.0 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Антон\AppData\Roaming\npm-cache\_logs\2021-11-29T19_07_46_812Z-debug.log

**Comment by gjcope** [comment]
Hi @Antonkl22 ,

From your output it looks like you don't have a correctly formatted tools.json file. This is the config file used to point to all the tools visible to Cook. So this should be updated with the appropriate paths and version numbers for your local system. If you have any further issues, feel free to attach your tools.json here and I will take a look.

**Comment by Antonkl22** [comment]
Yes, of course. Here it is.
Could you, please, tell me what should i add into tools.json file?
I have installed only Reality capture. Should i install other applications, like FBX2glTF, ImageMagick, InstantMeshes, and others?

{
  "FBX2glTF": {
    "executable": "C:\\Tools\\FBX2glTF.exe",
    "version": "2.0",
    "maxInstances": 1,
    "timeout": 60 // 1 minute
  },
  "ImageMagick": {
    "executable": "C:\\Program Files\\ImageMagick-7.0.7-Q16\\magick.exe",
    "version": "7.0.7",
    "maxInstances": 1,
    "timeout": 600 // 10 minutes
  },
  "InstantMeshes": {
    "executable": "C:\\Tools\\Instant Meshes.exe",
    "version": "",
    "maxInstances": 1,
    "timeout": 900 // 15 minutes
  },
  "MeshSmith": {
    "executable": "C:\\Tools\\MeshSmith\\MeshSmith.exe",
    "version": "v0.6.4, 2019-05-04",
    "maxInstances": 3,
    "timeout": 600 // 10 minutes
  },
  "Meshfix": {
    "executable": "C:\\Tools\\MeshFix.exe",
    "version": "v2.1",
    "maxInstances": 1,
    "timeout": 600 // 10 minutes
  },
  "Meshlab": {
    "executable": "C:\\Tools\\MeshlabMini\\meshlabserver.exe",
    "version": "v2019.5, 2019-05-02",
    "maxInstances": 3,
    "timeout": 1800 // 30 minutes
  },
  "RapidCompact": {
    "executable": "C:\\Program Files\\RapidCompact CLI 1.6.0\\rpdx.exe",
    "version": "1.6",
    "maxInstances": 3,
    "timeout": 900 // 15 minutes
  },
  "RealityCapture": {
    "executable": "C:\\Program Files\\Capturing Reality\\RealityCapture\\RealityCapture.exe",
    "version": "1.0.3.4658",
    "maxInstances": 1,
    "timeout": 0 // never
  },
  "RizomUV": {
    "executable": "C:\\Program Files\\Rizom Lab\\RizomUV VS RS 2018.0\\rizomuv.exe",
    "version": "RizomUV_VSRS.2018.0.85.g41754c4.master",
    "maxInstances": 2,
    "timeout": 1800 // 30 minutes
  },
  "XNormal": {
    "executable": "C:\\Program Files\\xNormal\\3.19.3\\x64\\xNormal.exe",
    "version": "3.19.3.39669",
    "maxInstances": 1,
    "timeout": 2700 // 45 minutes
  }
}

**Comment by gjcope** [comment]
You can put a number in the "version" attribute of "InstantMeshes", or if you aren't using it in your pipeline, just comment that block out or remove it all together.

Also FYI, we don't actually have any public recipes available yet that make use of RealityCapture.

**Comment by Antonkl22** [comment]
> 

I am really sorry, but could you, please send the code of the "correctly formatted tools.json file"? I am really broke my head by trying to launch the cook... =(

**Comment by gjcope** [comment]
In the block for the "InstantMeshes" application (shown below) just add a version. Or if you aren't using that application, just delete the section shown below from the tools.json file.

`"InstantMeshes": {
"executable": "C:\Tools\Instant Meshes.exe",
"version": "1.0",
"maxInstances": 1,
"timeout": 900 // 15 minutes
},`
